# Generated by Django 5.0 on 2023-12-12 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_url_a', models.URLField()),
                ('pattern_url_b', models.URLField()),
                ('pattern_preview', models.URLField()),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FlashesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashes_name', models.CharField(max_length=64)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('public', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.color')),
                ('flashes_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirts_created', to='danflashesapi.flashesuser')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashes_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.flashesuser')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_favorite', to='danflashesapi.shirt')),
            ],
        ),
        migrations.AddField(
            model_name='shirt',
            name='favorites',
            field=models.ManyToManyField(through='danflashesapi.ShirtFavorite', to='danflashesapi.flashesuser'),
        ),
        migrations.CreateModel(
            name='ShirtPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_index', models.SmallIntegerField(null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.pattern')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_pattern', to='danflashesapi.shirt')),
            ],
        ),
        migrations.AddField(
            model_name='shirt',
            name='patterns',
            field=models.ManyToManyField(through='danflashesapi.ShirtPattern', to='danflashesapi.pattern'),
        ),
    ]
