# Generated by Django 5.0 on 2024-01-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shirtpattern',
            unique_together={('shirt', 'pattern_index')},
        ),
    ]
