# Generated by Django 5.0 on 2023-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_url_a', models.URLField()),
                ('pattern_url_b', models.URLField()),
                ('label', models.CharField(max_length=64)),
            ],
        ),
    ]
