# Generated by Django 5.0 on 2023-12-04 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0003_flashesuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('public', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.color')),
                ('flashes_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirts_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShirtPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_index', models.SmallIntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.pattern')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.shirt')),
            ],
        ),
        migrations.AddField(
            model_name='shirt',
            name='patterns',
            field=models.ManyToManyField(through='danflashesapi.ShirtPattern', to='danflashesapi.pattern'),
        ),
    ]
