# Generated by Django 5.0 on 2023-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0004_shirt_shirtpattern_shirt_patterns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtpattern',
            name='pattern_index',
            field=models.SmallIntegerField(null=True),
        ),
    ]
