# Generated by Django 5.0 on 2023-12-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0005_alter_shirtpattern_pattern_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashes_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.flashesuser')),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danflashesapi.shirt')),
            ],
        ),
        migrations.AddField(
            model_name='shirt',
            name='favorites',
            field=models.ManyToManyField(through='danflashesapi.ShirtFavorite', to='danflashesapi.flashesuser'),
        ),
    ]
