# Generated by Django 5.0 on 2023-12-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0006_shirtfavorite_shirt_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtfavorite',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_favorite', to='danflashesapi.shirt'),
        ),
        migrations.AlterField(
            model_name='shirtpattern',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_pattern', to='danflashesapi.shirt'),
        ),
    ]
