# Generated by Django 5.0 on 2023-12-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0007_alter_shirtfavorite_shirt_alter_shirtpattern_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='flashes_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirts_created', to='danflashesapi.flashesuser'),
        ),
    ]
