# Generated by Django 5.0 on 2023-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danflashesapi', '0008_alter_shirt_flashes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='pattern_preview',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
